export { default as CLayout } from './CLayout/CLayout'
export { default as CDashboard } from './CDashboard/CDashboard'
export { default as Logement } from './Logement/Logement'
export { default as LogementAdd } from './Logement/LogementAdd/LogementAdd'
export { default as LogementEdit } from './Logement/LogementEdit/LogementEdit'
export { default as UserLogement } from './Logement/UserLogement/UserLogement'